FROM node:16 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install --production

RUN git clone https://github.com/mapbox/node-sqlite3.git \
    && cd ./node-sqlite3 \
    && npm install \
    && npm install mocha@9.1.3 \
    && cd ..

COPY . .

RUN mkdir -p ./public ./data \
    && npm install ./node-sqlite3 \
    && cd ./client \
    && npm install --production \
    && npm run build \
    && cd .. \
    && mv ./client/build/* ./public \
    && rm -rf ./client

FROM node:16-alpine

COPY --from=builder /app /app

WORKDIR /app

EXPOSE 5005

ENV NODE_ENV=production
ENV PASSWORD=flame_password

CMD ["sh", "-c", "chown -R node /app/data && node server.js"]