FROM node:16 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

RUN git clone https://github.com/TryGhost/node-sqlite3.git \
    && cd ./node-sqlite3 \
    && npm install --omit=dev \
    && cd ..

COPY . .

RUN mkdir -p ./public ./data \
    && npm install ./node-sqlite3 \
    && cd ./client \
    && npm install --omit=dev \
    && npm run build \
    && cd .. \
    && mv ./client/build/* ./public \
    && rm -rf ./client \
    && npm rebuild

FROM node:16-alpine

COPY --from=builder /app /app

WORKDIR /app

EXPOSE 5005

ENV NODE_ENV=production
#ENV PASSWORD=flame_password

CMD ["sh", "-c", "chown -R node /app/data && node server.js"]